

bot:
  token: "YOUR_BOT_TOKEN"
  channelId: YOUR_CHANNEL_ID
  discordFormat: "**%s** -> %s"
  chatFormat: "[Discord] %s -> %s"

# üì¢ Messaggio broadcast globale (es. killstreak, messaggi importanti, etc.)
broadcast:
  format: '&#F45454 ô&#F5694A Ä&#F67F3F·¥è&#F79435·¥Ä&#F8AA2A·¥Ö&#F9BF20·¥Ñ&#FAD415·¥Ä&#FBEA0Bs&#FCFF00·¥õ &7%message%'
  console: false